// Generated by CoffeeScript 1.3.3
(function() {
  var createWorm, i, wormEmitter, wormNum;

  i = 0;

  wormNum = 4;

  wormEmitter = function(x, y) {
    var w;
    return w = self.setInterval(function() {
      i++;
      wormNum--;
      if (wormNum <= 0) {
        clearInterval(w);
      }
      console.log(wormNum);
      return createWorm(x, y, i);
    }, 3000);
  };

  createWorm = function(x, y, i) {
    var dir, sprite, windowH, windowW;
    windowH = $(window).height();
    windowW = $(window).width();
    dir = x > windowW / 2 ? 'l' : 'r';
    if (x > windowW / 2) {
      x += 100;
    } else {
      x -= 100;
    }
    sprite = "worm_crawl_" + dir + ".gif";
    return setTimeout(function() {
      var worm;
      $("body").prepend("<img id='" + i + "' class='worm' src='" + sprite + "' />");
      worm = $("#" + i);
      worm.css({
        'left': x
      }, {
        'top': y
      });
      return worm.animate({
        'left': windowW / 2,
        'top': windowH / 2
      }, Math.random() * 6000 + 8000);
    }, Math.random() * 500 + 2000);
  };

  window.startGame = function() {
    var windowH, windowW;
    windowH = $(window).height();
    windowW = $(window).width();
    wormEmitter(windowW, 0);
    wormEmitter(0, 0);
    return $('audio#worm-loop').trigger('play');
  };

}).call(this);
