// Generated by CoffeeScript 1.3.3
(function() {
  var menuAnimation, setupMenu;

  jQuery.ready = function() {
    return menuAnimation();
  };

  $(window).resize(function() {});

  menuAnimation = function() {
    var height, jake, width;
    height = $(window).height();
    width = $(window).width();
    jake = $('#sitting-jake');
    jake.css({
      'top': height,
      'left': (width / 2) - 180
    });
    $('span.menu-option').css({
      'left': (width / 2) - 120,
      'top': height + 50
    });
    return jake.animate({
      'top': (height / 2) - 100
    }, 1000, function() {
      var jakePos;
      jakePos = jake.position();
      $('span#menu-newgame').animate({
        'left': jakePos.left - 80,
        'top': jakePos.top + 30
      }, 500);
      $('span#menu-password').animate({
        'left': jakePos.left + 320,
        'top': jakePos.top + 30
      }, 500);
      return $('span#menu-info').animate({
        'left': jakePos.left + 100,
        'top': jakePos.top - 20
      }, 800, function() {
        return setupMenu();
      });
    });
  };

  setupMenu = function() {
    $('span.menu-option').hover(function() {
      return $(this).css({
        'cursor': 'pointer'
      });
    });
    $('span#menu-newgame').click(function() {});
    $('span#menu-password').click(function() {
      return $('div#password-div').slideDown(500);
    });
    return $('span#menu-info').click(function() {});
  };

}).call(this);
