// Generated by CoffeeScript 1.3.3
(function() {
  var createWorm, emitterActive, endRound, i, once, round, score, startRound, wormBirth, wormEmitter, wormRate;

  i = 0;

  score = 0;

  wormRate = 5000;

  round = 1;

  wormBirth = false;

  once = true;

  emitterActive = false;

  wormEmitter = function(x, y, num) {
    var w;
    self.wormNum = num * 9;
    emitterActive = true;
    return w = self.setInterval(function() {
      i++;
      self.wormNum--;
      if (self.wormNum <= 0) {
        clearInterval(w);
        return emitterActive = false;
      } else if (round < 6) {
        return createWorm(x, y, i);
      }
    }, wormRate);
  };

  createWorm = function(x, y, i) {
    var dir, dirOffset, jake, jakeH, jakePos, jakeW, sprite, windowH, windowW;
    windowH = $(window).height();
    windowW = $(window).width();
    jake = $('#sitting-jake');
    jakePos = jake.position();
    jakeW = jake.width();
    jakeH = jake.height();
    dir = x > windowW / 2 ? 'l' : 'r';
    if (x > windowW / 2) {
      x += 100;
      dirOffset = jakeW * .7;
    } else {
      x -= 100;
      dirOffset = -1 * jakeW * .7;
    }
    sprite = "imgs/worm_crawl_" + dir + ".gif";
    return setTimeout(function() {
      var worm;
      $("body").append("<img id='" + i + "' class='worm' src='" + sprite + "' />");
      wormBirth = true;
      worm = $("#" + i);
      worm.css({
        'left': x
      }, {
        'top': y
      });
      worm.animate({
        'left': jakePos.left + dirOffset,
        'top': jakePos.top + .1 * jakeH
      }, (Math.random() * 6000 + 5500) - round * 600, 'linear', function() {
        var scoreSpan;
        worm.attr('src', "imgs/worm_bite_" + dir + ".gif");
        $('audio#worm-wowow').trigger('play');
        $("body").append("<span id='score-" + i + "' class='score'>-10</span>");
        score -= 10;
        scoreSpan = $("#score-" + i);
        scoreSpan.css({
          'color': 'red',
          'top': jakePos.top - 50,
          'left': jakePos.left + 20,
          'z-index': -i - 5
        });
        worm.fadeOut(900, function() {
          return worm.remove();
        });
        return scoreSpan.fadeOut(900, function() {
          return scoreSpan.remove();
        });
      });
      return worm.mousedown(function(e) {
        var scoreSpan;
        worm.unbind('mousedown');
        $('audio#zap').trigger('play');
        worm.stop().attr('src', "imgs/worm_stand_" + dir + ".gif");
        worm.css({
          'z-index': -i
        });
        if (!($("#score-" + i).length > 0)) {
          $("body").append("<span id='score-" + i + "' class='score'>+10</span>");
        }
        score += 10;
        scoreSpan = $("#score-" + i);
        scoreSpan.css({
          'top': e.pageY - 50,
          'left': e.pageX
        });
        worm.fadeOut(500, function() {
          return worm.remove();
        });
        return scoreSpan.animate({
          'top': '20px'
        }, 200).fadeOut(800, function() {
          return scoreSpan.remove();
        });
      });
    }, Math.random() * 500 + 2000);
  };

  startRound = function() {
    var check, windowH, windowW;
    windowH = $(window).height();
    windowW = $(window).width();
    wormEmitter(windowW, 0, round);
    wormEmitter(0, 0, round);
    $('audio#worm-loop').trigger('play');
    if (!(round > 5)) {
      $("audio#kw-taunt-" + round).trigger('play');
    }
    clearInterval(check);
    return check = setInterval(function() {
      if (round === 6) {
        endRound();
        once = false;
        return clearInterval(check);
      } else if ($('.worm').length === 0 && wormBirth === true && !emitterActive) {
        $('audio#worm-loop').trigger('pause');
        round++;
        if (!(round > 5)) {
          message("Round " + round, '', 3);
        }
        wormRate -= 1000;
        wormBirth = false;
        return startRound();
      }
    }, 1000);
  };

  endRound = function() {
    var finalMsg;
    if (once) {
      wormBirth = false;
      $('audio#worm-loop').trigger('pause');
      $('audio#wormlevel-music').trigger('pause');
      $('audio#menu-loop').trigger('play');
      finalMsg = "Your score of " + score + " ";
      finalMsg += score > 1000 ? "is good, the password is `pits`" : "is not so good, try again.";
      if (score < 0) {
        finalMsg += "  You didn't even try did you?";
      }
      return message("Final Score: " + score, finalMsg, -1);
    }
  };

  window.startGame = function() {
    i = 0;
    score = 0;
    wormRate = 5000;
    round = 1;
    wormBirth = false;
    once = true;
    emitterActive = false;
    $('audio#menu-loop').trigger('pause');
    $('audio#wormlevel-music').trigger('play');
    startRound();
    message("Round " + round, 'Click the wittle wormies to zap them from your consciousness', 7);
    return $('body').css({
      'background-image': 'url(\'imgs/kingworm.svg\')',
      'background-repeat': 'no-repeat',
      'background-position': 'center',
      'background-attachment': 'fixed'
    });
  };

}).call(this);
